In [88]:
#shrroms
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format

In [89]:
df = pd.read_csv(r"estimation+of+obesity+levels+based+on+eating+habits+and+physical+condition\ObesityDataSet_raw_and_data_sinthetic.csv")
df.head()
y = df["NObeyesdad"]

In [91]:
#df.pop("NObeyesdad")
y.unique()
from sklearn.preprocessing import LabelEncoder
a = LabelEncoder().fit_transform(y)
#pd.DataFrame([y, a])
y = a

In [27]:
num_col = df.describe().columns
num_col
cat_col = list(set(df.columns) - set(num_col))
df_num = df[num_col]
df_cat = df[cat_col]



Age    Height      Weight  FCVC  NCP      CH2O       FAF       TUE
0     21.000000  1.620000   64.000000   2.0  3.0  2.000000  0.000000  1.000000
1     21.000000  1.520000   56.000000   3.0  3.0  3.000000  3.000000  0.000000
2     23.000000  1.800000   77.000000   2.0  3.0  2.000000  2.000000  1.000000
3     27.000000  1.800000   87.000000   3.0  3.0  2.000000  2.000000  0.000000
4     22.000000  1.780000   89.800000   2.0  1.0  2.000000  0.000000  0.000000
...         ...       ...         ...   ...  ...       ...       ...       ...
2106  20.976842  1.710730  131.408528   3.0  3.0  1.728139  1.676269  0.906247
2107  21.982942  1.748584  133.742943   3.0  3.0  2.005130  1.341390  0.599270
2108  22.524036  1.752206  133.689352   3.0  3.0  2.054193  1.414209  0.646288
2109  24.361936  1.739450  133.346641   3.0  3.0  2.852339  1.139107  0.586035
2110  23.664709  1.738836  133.472641   3.0  3.0  2.863513  1.026452  0.714137

[2111 rows x 8 columns]

In [30]:
df_cat_enc = pd.get_dummies(df_cat, dtype=int )
df_cat_enc


Age  Height  Weight  FCVC  NCP  CH2O  FAF  TUE
0    21.00    1.62   64.00  2.00 3.00  2.00 0.00 1.00
1    21.00    1.52   56.00  3.00 3.00  3.00 3.00 0.00
2    23.00    1.80   77.00  2.00 3.00  2.00 2.00 1.00
3    27.00    1.80   87.00  3.00 3.00  2.00 2.00 0.00
4    22.00    1.78   89.80  2.00 1.00  2.00 0.00 0.00
...    ...     ...     ...   ...  ...   ...  ...  ...
2106 20.98    1.71  131.41  3.00 3.00  1.73 1.68 0.91
2107 21.98    1.75  133.74  3.00 3.00  2.01 1.34 0.60
2108 22.52    1.75  133.69  3.00 3.00  2.05 1.41 0.65
2109 24.36    1.74  133.35  3.00 3.00  2.85 1.14 0.59
2110 23.66    1.74  133.47  3.00 3.00  2.86 1.03 0.71

[2111 rows x 8 columns]

In [43]:
from sklearn.preprocessing import StandardScaler
df_num_sc = StandardScaler().fit_transform(df_num)
df_num_sc1 = pd.DataFrame(df_num_sc, columns=num_col)
X = pd.concat([df_num, df_cat_enc], axis=1)


In [74]:
from sklearn.model_selection import  train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
X_train_num = X_train[num_col]
X_train_cat = X_train[df_cat_enc.columns]
sc = StandardScaler()
sc.fit(X_train_num)
X_train_num_sc = sc.transform(X_train_num)
X_train = X_train.values
X_train[:, [0,1,2,3,4,5,6,7]] = X_train_num_sc
X_train_sc = pd.DataFrame(X_train, columns=X.columns)
X_train_sc

Age  Height  Weight  FCVC   NCP  CH2O   FAF   TUE  CALC_Always  \
0    -0.17    0.55    1.25 -1.01  0.40 -0.02  1.07  0.50         0.00   
1    -0.51   -0.68   -0.64 -0.80 -2.14  0.17 -0.29 -1.06         0.00   
2    -1.13    0.05    0.49 -0.80  0.40 -0.02  0.85 -0.98         0.00   
3     1.68    0.82    0.54 -0.67 -1.54  1.59  1.23 -0.91         0.00   
4    -0.99    0.69   -1.36  0.54  0.40 -0.22  0.24  0.60         0.00   
...    ...     ...     ...   ...   ...   ...   ...   ...          ...   
1472 -0.63   -0.03    0.45 -0.80 -0.37 -0.02 -1.21  1.95         0.00   
1473 -0.53    1.88   -0.11  1.10  0.40  1.59  1.17  0.60         0.00   
1474 -0.42   -0.46   -0.26 -0.80  0.40 -0.02  2.28  1.76         0.00   
1475 -0.53    0.51   -0.34 -0.80  0.40 -0.02 -1.21  2.27         0.00   
1476 -0.44   -0.03    1.77  1.10  0.40 -0.45  0.90  0.47         0.00   

      CALC_Frequently  ...  family_history_with_overweight_no  \
0                0.00  ...                               0.00   
1                0.00  ...                               1.00   
2                0.00  ...                               0.00   
3                1.00  ...                               0.00   
4                0.00  ...                               0.00   
...               ...  ...                                ...   
1472             0.00  ...                               0.00   
1473             0.00  ...                               0.00   
1474             0.00  ...                               0.00   
1475             1.00  ...                               0.00   
1476             0.00  ...                               0.00   

      family_history_with_overweight_yes  SCC_no  SCC_yes  SMOKE_no  \
0                                   1.00    1.00     0.00      1.00   
1                                   0.00    1.00     0.00      1.00   
2                                   1.00    1.00     0.00      1.00   
3                                   1.00    1.00     0.00      1.00   
4                                   1.00    1.00     0.00      1.00   
...                                  ...     ...      ...       ...   
1472                                1.00    1.00     0.00      1.00   
1473                                1.00    1.00     0.00      1.00   
1474                                1.00    1.00     0.00      1.00   
1475                                1.00    0.00     1.00      1.00   
1476                                1.00    1.00     0.00      1.00   

      SMOKE_yes  CAEC_Always  CAEC_Frequently  CAEC_Sometimes  CAEC_no  
0          0.00         0.00             0.00            1.00     0.00  
1          0.00         0.00             0.00            0.00     1.00  
2          0.00         0.00             0.00            1.00     0.00  
3          0.00         0.00             0.00            1.00     0.00  
4          0.00         0.00             0.00            1.00     0.00  
...         ...          ...              ...             ...      ...  
1472       0.00         0.00             0.00            1.00     0.00  
1473       0.00         0.00             0.00            1.00     0.00  
1474       0.00         0.00             0.00            1.00     0.00  
1475       0.00         0.00             1.00            0.00     0.00  
1476       0.00         0.00             0.00            1.00     0.00  

[1477 rows x 31 columns]

In [80]:
X_test_num = X_test[num_col]
X_test_cat = X_test[df_cat_enc.columns]

X_test_num_sc = sc.transform(X_test_num)
X_test = X_test.values
X_test[:, [0,1,2,3,4,5,6,7]] = X_test_num_sc
X_test_sc = pd.DataFrame(X_test, columns=X.columns)
X_test_sc

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [83]:
X_test_sc.shape

(634, 31)

In [76]:
from sklearn.svm import SVC
svc = SVC(kernel="rbf", gamma = 0.1, C=1)
svc.fit(X_train_sc, y_train)


SVC(C=1, gamma=0.1)

In [94]:
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix, roc_auc_score
def print_score(clf, X_train, X_test, y_train, y_test, train=True):
    '''
    v0.1 Follow the scikit learn library format in terms of input
    print the accuracy score, classification report and confusion matrix of classifier
    '''
    
    if train:
        '''
        training performance
        '''
        res = clf.predict(X_train)
        print("Train Result:\n")
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_train, 
                                                                res)))
        print("Classification Report: \n {}\n".format(classification_report(y_train, 
                                                                            res)))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_train, 
                                                                  res)))
        #print("ROC AUC: {0:.4f}\n".format(roc_auc_score((y_train), 
        #                                              (res))))

        res = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))
        
    elif train==False:
        '''
        test performance
        '''
        res_test = clf.predict(X_test)
        print("Test Result:\n")        
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, 
                                                                res_test)))
        print("Classification Report: \n {}\n".format(classification_report(y_test, 
                                                                            res_test)))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, 
                                                                  res_test)))   
        
        res = cross_val_score(clf, X_test, y_test, cv=10, scoring='accuracy')
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))
        

In [96]:
print_score(svc, X_train_sc, X_test_sc, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9682

Classification Report: 
               precision    recall  f1-score   support

           0       0.98      0.99      0.99       190
           1       0.95      0.92      0.93       190
           2       0.98      0.99      0.99       250
           3       1.00      1.00      1.00       214
           4       1.00      1.00      1.00       225
           5       0.90      0.95      0.92       212
           6       0.97      0.92      0.94       196

    accuracy                           0.97      1477
   macro avg       0.97      0.97      0.97      1477
weighted avg       0.97      0.97      0.97      1477


Confusion Matrix: 
 [[189   1   0   0   0   0   0]
 [  4 175   0   0   0   9   2]
 [  0   0 247   1   0   2   0]
 [  0   0   1 213   0   0   0]
 [  0   0   0   0 225   0   0]
 [  0   6   1   0   0 201   4]
 [  0   3   2   0   0  11 180]]

Average Accuracy: 	 0.9079
Accuracy SD: 		 0.0261


In [97]:
from sklearn.model_selection import GridSearchCV
param = {"C":[1, 0.1, 0.01, 0.001, 0.0001],
         "gamma" : ["auto", "scale"]}
grid1 = GridSearchCV(SVC(), param, n_jobs=1, verbose=4, cv=5)
grid1.fit(X_train_sc, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END ...................C=1, gamma=auto;, score=0.868 total time=   0.3s
[CV 2/5] END ...................C=1, gamma=auto;, score=0.889 total time=   0.4s
[CV 3/5] END ...................C=1, gamma=auto;, score=0.831 total time=   0.4s
[CV 4/5] END ...................C=1, gamma=auto;, score=0.844 total time=   0.6s
[CV 5/5] END ...................C=1, gamma=auto;, score=0.892 total time=   0.5s
[CV 1/5] END ..................C=1, gamma=scale;, score=0.909 total time=   0.5s
[CV 2/5] END ..................C=1, gamma=scale;, score=0.909 total time=   0.5s
[CV 3/5] END ..................C=1, gamma=scale;, score=0.871 total time=   0.4s
[CV 4/5] END ..................C=1, gamma=scale;, score=0.864 total time=   0.4s
[CV 5/5] END ..................C=1, gamma=scale;, score=0.919 total time=   0.4s
[CV 1/5] END .................C=0.1, gamma=auto;, score=0.611 total time=   0.9s
[CV 2/5] END .................C=0.1, gamma=auto;

GridSearchCV(cv=5, estimator=SVC(), n_jobs=1,
             param_grid={'C': [1, 0.1, 0.01, 0.001, 0.0001],
                         'gamma': ['auto', 'scale']},
             verbose=4)

In [100]:
grid1.best_score_
grid1.best_params_
svc = SVC(kernel="rbf", C=1, gamma="scale")


In [102]:
from sklearn.ensemble import BaggingClassifier
bag = BaggingClassifier(estimator=svc, n_estimators=200,bootstrap=True, oob_score=True, warm_start=False)
bag.fit(X_train_sc, y_train)

BaggingClassifier(estimator=SVC(C=1), n_estimators=200, oob_score=True)

In [103]:
print_score(bag, X_train_sc, X_test_sc, y_train, y_test, train=True)

Train Result:

accuracy score: 0.9601

Classification Report: 
               precision    recall  f1-score   support

           0       0.98      0.99      0.99       190
           1       0.94      0.92      0.93       190
           2       0.98      0.98      0.98       250
           3       0.98      1.00      0.99       214
           4       1.00      1.00      1.00       225
           5       0.89      0.92      0.91       212
           6       0.94      0.91      0.92       196

    accuracy                           0.96      1477
   macro avg       0.96      0.96      0.96      1477
weighted avg       0.96      0.96      0.96      1477


Confusion Matrix: 
 [[189   1   0   0   0   0   0]
 [  4 174   0   0   0   9   3]
 [  0   0 244   4   0   2   0]
 [  0   0   1 213   0   0   0]
 [  0   0   0   0 225   0   0]
 [  0   8   1   0   0 195   8]
 [  0   3   3   0   0  12 178]]



KeyboardInterrupt: 